#!/usr/bin/env bash

# @brief dreport plugins functions.
#
# This file is part of the CLI project.
#
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 YADRO
#
# @author: Alexander Soldatov <a.soldatov@yadro.com>
# @author: Alexander Filippov <a.filippov@yadro.com>

# @brief output command result to stdout
# @param command
function add_cmd_output()
{
    eval "${1}" | cat
}

# @brief output file content to stdout
# @param file fullname
function add_copy_file()
{
    local file_name="$1"
    if [[ -f $file_name ]]; then
      cat "$file_name"
    elif [[ -d $file_name ]]; then
      zcat "$file_name"/*.gz
    else
      echo "Not a log: ${file_name}"
    fi
}

# @brief Copy the symbolic link file to the dreport packaging,
#        if it is in the user allowed dump size limit.
# @param $1 symbolic link file name
# @param $2 Plugin description used for logging.
function add_copy_sym_link_file()
{
    add_copy_file "$(realpath "${1}")" "${2}"
}

# @brief log the error message
# @param error message
function log_error()
{
   echo "$($TIME_STAMP) ERROR: " "$@"
}

# @brief log warning message
# @param warning message
function log_warning()
{
    # `verbose` comes from the caller (dreport), calm shellcheck about it
    # shellcheck disable=SC2154
    if ((verbose == TRUE)); then
        echo "$($TIME_STAMP) WARNING: " "$@"
    fi
}

# @brief log info message
# @param info message
function log_info()
{
    # `verbose` comes from the caller (dreport), calm shellcheck about it
    # shellcheck disable=SC2154
    if ((verbose == TRUE)); then
        echo "$($TIME_STAMP) INFO: " "$@"
    fi
}

# @brief log mmary message
# @param message
function log_summary()
{
    echo "$($TIME_STAMP) " "$@"
}

