#!/bin/bash -eu
#
# YADRO OpenBMC Command Line Interface
# Copyright (C) 2020-2021 YADRO
#
# SPDX-License-Identifier: Apache-2.0
#

# CLI: User management

GROUP_IPMI="ipmi"
GROUP_REDFISH="redfish"
GROUP_WEB="web"
GROUP_SSH="ssh"

# D-Bus entities to manage user accounts
DBUS_SERVICE="xyz.openbmc_project.User.Manager"
DBUS_ROOT_PATH="/xyz/openbmc_project/user"
DBUS_ATTRIBUTES="xyz.openbmc_project.User.Attributes"
DBUS_DELETE="xyz.openbmc_project.Object.Delete"

USERNAME_REGEX="^[\.a-zA-Z0-9_-]+$"

# This one us used in help, need to output a single word of role
# and nothing else. Please do not 'beautify'.
#
# @doc cmd_myrole
# Show the role of the current user
function cmd_myrole {
  group_to_role "${GROUP}"
}

# @sudo cmd_create admin
# @restrict cmd_create admin
# @doc cmd_create
# Create a new user
#   -n, --name NAME - User name
#   -r, --role ROLE - Role for user (admin, operator or user)
function cmd_create {
  local name=""
  local role="${ROLE_USER}"
  if [[ $# -eq 0 ]]; then
    user create help
    return 1
  fi

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -n | --name)
        [[ $# -gt 1 ]] || abort_badarg "Name is not specified"
        name="$2"
        shift
        ;;
      -r | --role)
        [[ $# -gt 1 ]] || abort_badarg "Role is not specified"
        role="$2"
        shift
        ;;
      *) abort_badarg "$1";;
    esac
    shift
  done
  if [[ ! ${name} =~ ${USERNAME_REGEX} ]]; then
    echo "Invalid user name: ${name}" >&2
    return 1
  fi

  local priv
  priv=$(role_to_group "${role}")
 
  busctl call ${DBUS_SERVICE} ${DBUS_ROOT_PATH} \
              ${DBUS_SERVICE} CreateUser sassb \
              "${name}" \
              4 ${GROUP_IPMI} ${GROUP_REDFISH} ${GROUP_WEB} ${GROUP_SSH} \
              "${priv}" \
              true
  echo "User ${name} created."
}

# @sudo cmd_show admin
# @restrict cmd_show admin
# @doc cmd_show
# Show specific user
#   USERNAME... - Show user with specific name (multiple names can be added)
function cmd_show {
  while [[ $# -gt 0 ]]; do
    local user="$1"
    shift
    local grp
    grp=$(busctl get-property ${DBUS_SERVICE} "${DBUS_ROOT_PATH}/${user}" \
                               ${DBUS_ATTRIBUTES} "UserPrivilege" \
                               2>/dev/null \
          | awk '{gsub(/"/, "", $NF); print $NF}')
    if [[ -z "${grp}" ]]; then
      echo "Invalid user: ${user}" >&2
      return 1
    fi
    local role
    role=$(group_to_role "${grp}")
    echo "${user}: ${role}"
  done
}

# @sudo cmd_list admin
# @restrict cmd_list admin
# @doc cmd_list
# Show list of users
function cmd_list {
  local path
  for path in $(busctl --list tree ${DBUS_SERVICE} | grep ${DBUS_ROOT_PATH}/); do
    cmd_show "${path##*/}"
  done
}

# @sudo cmd_delete admin
# @restrict cmd_delete admin
# @doc cmd_delete
# Delete users
#   -y, --yes   - Do not ask for confirmation
#   USERNAME... - User account name (multiple names can be added)
function cmd_delete {
  local yes=""
  local names=()

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -y | --yes) yes="y";;
      *)
        if [[ $1 =~ ${USERNAME_REGEX} ]]; then
          names+=( "$1" )
        else
          abort_badarg "$1"
        fi
        ;;
    esac
    shift
  done

  if [[ ${#names[@]} -lt 1 ]]; then
    echo "User name is not specified" >&2
    return 1
  fi

  if [[ "${names[*]}" =~ 'admin' ]]; then
    echo "Admin is a built-in user and cannot be removed!" >&2
    return 1
  fi

  if [[ "${names[*]}" =~ ${SUDO_USER:-${USER}} ]]; then
    echo "You cannot remove yourself" >&2
    return 1
  fi

  if [[ -z "${yes}" ]]; then
    if [[ ${#names[@]} -eq 1 ]]; then
      echo "User '${names[0]}' will be removed permanently."
    else
      echo "${#names[@]} users will be removed permanently."
    fi
    confirm
  fi

  for name in "${names[@]}"; do
    if ! busctl call ${DBUS_SERVICE} "${DBUS_ROOT_PATH}/${name}" \
                     ${DBUS_DELETE} Delete 2>/dev/null; then
      echo "Error deleting user: ${name}" >&2
      return 1
    fi
    echo "User ${name} removed."
  done
}

# @doc cmd_set
# Operations with user account
function cmd_set {
  subcommand "$@"
}

# @sudo cmd_set_password admin
# @restrict cmd_set_password admin
# @doc cmd_set_password
# Update user password
#   USERNAME - User account name
function cmd_set_password {
  if [[ $# -eq 0 ]] || [[ -z "$1" ]]; then
    echo "User name is not specified" >&2
    return 1
  fi
  local name="$1"
  if [[ $(id -u "${name}") -lt 1000 ]]; then
    echo "Invalid user: ${name}" >&2
    return 1
  fi
  passwd "${name}"
}

# @doc cmd_set_mypassword
# Change own password
function cmd_set_mypassword {
  expect_noarg "$@"
  passwd
}

# @sudo cmd_set_role admin
# @restrict cmd_set_role admin
# @doc cmd_set_role
# Update user role
#   -n, --name NAME - User name
#   -r, --role ROLE - Role for user (admin, operator or user)
function cmd_set_role {
  local name=""
  local role=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -n | --name)
        [[ $# -gt 1 ]] || abort_badarg "Name is not specified"
        name="$2"
        shift
        ;;
      -r | --role)
        [[ $# -gt 1 ]] || abort_badarg "Role is not specified"
        role="$2"
        shift
        ;;
      *) abort_badarg "$1";;
    esac
    shift
  done

  if [[ -z "${name}" ]]; then
    echo "User name not specified" >&2
    return 1
  fi
  if [[ -z "${role}" ]]; then
    echo "Role name not specified" >&2
    return 1
  fi

  if [[ "${name}" =~ 'admin' ]]; then
    echo "Admin is a built-in user and cannot be changed!" >&2
    return 1
  fi

  if [[ "${name}" =~ ${SUDO_USER:-${USER}} ]]; then
    echo "You cannot change your own role" >&2
    return 1
  fi

  local priv
  priv=$(role_to_group "${role}")

  busctl set-property ${DBUS_SERVICE} "${DBUS_ROOT_PATH}/${name}" \
                      ${DBUS_ATTRIBUTES} "UserPrivilege" s "${priv}"

  echo "User ${name} now has ${role} privileges."
}
