#!/bin/bash -eu

#
# BMC config backup/restore.
#

# prevent modification of executable path
PATH="/bin:/sbin:/usr/bin:/usr/sbin"

# elevate self privileges
[[ ${EUID} -eq 0 ]] || exec sudo $(realpath ${BASH_SOURCE[0]}) $@

# list of files to save/restore
WHITELIST="/var/run/initramfs/whitelist"

# parse command line options
if [[ $# -eq 0 ]]; then
  ACTION="help"
else
  ACTION="$1"
fi
case "${ACTION}" in
  help | -h | --help)
    echo "Backup or restore OpenBMC configuration."
    echo "Use: ${0##*/} [OPTION...]"
    echo "  backup FILE   Save configuration to file"
    echo "  restore FILE  Restore configuration from file"
    echo "  reset         Reset configuration to manufacturing default"
    echo "  -h, --help    Print this help and exit"
    ;;

  backup)
    if [[ $# -ne 2 ]]; then
      echo "File name is not specified" >&2
      exit 1
    fi
    shift
    BACKUP_FILE="$1"
    tar czf "${BACKUP_FILE}" -T ${WHITELIST} &>/dev/null || /bin/true
    if [[ -f ${BACKUP_FILE} ]]; then
      echo "Backup created: ${BACKUP_FILE}"
    else
      echo "Error creating backup: ${BACKUP_FILE}" >&2
      exit 1;
    fi
    ;;

  restore)
    if [[ $# -ne 2 ]]; then
      echo "File name is not specified" >&2
      exit 1
    fi
    shift
    BACKUP_FILE="$1"
    TMP_DIR="$(mktemp -d)"
    tar xf "${BACKUP_FILE}" -C ${TMP_DIR}
    for FILE in $(cat ${WHITELIST}); do
      [[ -e ${TMP_DIR}${FILE} ]] || continue
      rm -rf ${FILE} &>/dev/null || true
      mkdir -p $(dirname ${FILE})
      cp -r ${TMP_DIR}${FILE} ${FILE}
    done
    rm -rf ${TMP_DIR}
    echo "Restored from backup: $2"
    echo "Please, reboot the BMC."
    ;;

  reset)
    fwupdate --reset
    ;;

  * )
    echo "Invalid argument: $1" >&2
    exit 1
    ;;
esac
