#!/bin/bash -eu

#
# CLI: Chassis LED identify control
#

# D-Bus object descriptions to manage the LED
DBUS_SERVICE="xyz.openbmc_project.LED.GroupManager"
DBUS_OBJECT="/xyz/openbmc_project/led/groups/enclosure_identify"
DBUS_INTERFACE="xyz.openbmc_project.Led.Group"
DBUS_PROPERTY="Asserted"

# parse command line options
if [[ $# -eq 0 ]]; then
  ACTION="state"
elif [[ $# -eq 1 ]]; then
  case "$1" in
    -h | --help)
      echo "Chassis LED identify control."
      echo "Use: $0 [OPTION...] ACTION"
      echo "Actions:"
      echo "  on            Turn LED on"
      echo "  off           Turn LED off"
      echo "  state         Print current LED state and exit [default]"
      echo "Options:"
      echo "  -h, --help    Print this help and exit"
      exit 0
      ;;
    on | off | state)
      ACTION="$1"
      ;;
    *)
      echo "Invalid argument: $1" >&2
      exit 1
      ;;
  esac
else
  echo "Invalid arguments" >&2
  exit 1
fi

# set state
STATE=
case "${ACTION}" in
  on ) STATE="true";;
  off ) STATE="false";;
esac
if [[ -n "${STATE}" ]]; then
  busctl set-property ${DBUS_SERVICE} ${DBUS_OBJECT} \
                      ${DBUS_INTERFACE} ${DBUS_PROPERTY} \
                      b ${STATE}
fi

# print current state
STATE="$(busctl get-property ${DBUS_SERVICE} ${DBUS_OBJECT} \
                             ${DBUS_INTERFACE} ${DBUS_PROPERTY} \
                             | awk '{print $NF}')"
case "${STATE}" in
  true) STATE="ON";;
  false) STATE="OFF";;
  *) STATE="Unknown";;
esac
echo "Current LED state: ${STATE}"
