#!/bin/bash -eu

#
# CLI: Update BMC/BIOS firmware
#

function show_usage
{
    echo "Update BIOS/BMC firmware."
    echo "Use: $0 [OPTION...] FILE"
    echo "  -c, --clear   Reset BMC settings to manufacture defaults"
    echo "  -y, --yes     Do not ask for confirmation"
    echo "  -h, --help    Print this help and exit"
}

# parse command line options
FILE=
CLEAR=
YES=

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h | --help)
      show_usage
      exit 0
      ;;
    -c | --clear) CLEAR="$1";;
    -y | --yes) YES="$1";;
    -*)
        echo "Invalid argument" >&2
        show_usage
        exit 1
        ;;
    *)
      if [[ -n "${FILE}" ]]; then
        echo "Invalid argument, file already specified" >&2
        exit 1
      fi
      FILE="$1"
      ;;
  esac
  shift
done

if [[ -z "${FILE}" ]] && [[ -z "${CLEAR}" ]]; then
    show_usage
    exit 1
fi

CMD="fwupdate"
[[ -z "${YES}" ]] || CMD+=" --yes"
[[ -z "${CLEAR}" ]] || CMD+=" --reset"
exec ${CMD} -f "${FILE}"
