#!/bin/bash -eu

#
# CLI: Attach to the host's console
#

if [[ $# -gt 0 ]]; then
  case "$1" in
    -h | --help)
      echo "Host console access."
      echo "Use: $0 [OPTION...]"
      echo "  -h, --help    Print this help and exit"
      exit 0
      ;;
    *)
      echo "Invalid argument: $1" >&2
      exit 1
      ;;
  esac
fi

cat << EOF
Starting a Host console connection.
Send <CR>~. to terminate it.
If connected via SSH, add extra ~ characters, one per SSH connection.
EOF

exec obmc-console-client
