#!/bin/bash -eu

#
# CLI: Print inventory list
#

# prevent modification of executable path
PATH="/bin:/sbin:/usr/bin:/usr/sbin"

# elevate self privileges
[[ ${EUID} -eq 0 ]] || exec sudo $(realpath ${BASH_SOURCE[0]}) $@

exec lsinventory $@
